### ISSUE TITLE
error while fetching data ...

### ISSUE THREAD

**Issue by ASACHIT** [Samrid-Pandit/nepse-api#2]
![image](https://user-images.githubusercontent.com/73944456/120623004-0ba22b00-c47f-11eb-8226-555524c5c64e.png)
some symbols i used=**BBBLPO,HAMA** etc ...

**Comment by CaffeineDuck** [comment]
The symbols mentioned in this issue, **BBBLPO, HAMA, etc ...** are not in Nepse's API. Hence you were not able to fetch the data for the securities with those symbols. Make sure that those are valid symbols. And if you are sure that, those symbols were valid, it's an issue on the API side and I can't really do anything about it.
