### ISSUE TITLE
no modules named attr

### ISSUE THREAD

**Issue by ASACHIT** [Samrid-Pandit/nepse-api#33]
![image](https://user-images.githubusercontent.com/73944456/121407464-124d0880-c97f-11eb-87e8-14df873400f2.png)
To recreate issue-
just install nepse-api and run API with code .. and it will throw module missing error  attr and httpx.****

**Comment by CaffeineDuck** [comment]
Fixed in [v1.1.5-beta](https://github.com/Samrid-Pandit/nepse-api/releases/tag/v1.1.5-beta). Thanks for your contribution
